# Generated by Django 4.1.6 on 2023-04-03 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProduitApp', '0002_alter_autreproduit_prix_achat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autreproduit',
            name='prix_vente',
        ),
    ]
