# Generated by Django 4.1.6 on 2023-04-04 08:46

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProduitApp', '0004_alter_autreproduit_prix_achat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
        migrations.AlterField(
            model_name='produitbrut',
            name='prix_achat_barre',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produitbrut',
            name='prix_achat_metre',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produitbrut',
            name='prix_achat_quintal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produitbrut',
            name='prix_barre',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produitbrut',
            name='prix_metre',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produitbrut',
            name='prix_quintal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produitbrut',
            name='stock_barre',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produitbrut',
            name='stock_metre',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produitbrut',
            name='stock_quintal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
