# Generated by Django 4.1.6 on 2023-04-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProduitApp', '0005_alter_produit_prix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autreproduit',
            name='prix_vente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
