# Generated by Django 4.1.6 on 2023-04-06 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProduitApp', '0006_autreproduit_prix_vente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='prix',
        ),
    ]
