# Generated by Django 4.1.6 on 2023-04-06 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProduitApp', '0007_remove_produit_prix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadre',
            name='prix_metre',
        ),
    ]
