# Generated by Django 4.1.6 on 2023-03-27 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProduitApp', '__first__'),
        ('FournisseursApp', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_achat', models.DateTimeField()),
                ('categorie', models.CharField(max_length=50, null=True)),
                ('prix_total', models.FloatField()),
                ('Versement', models.FloatField(null=True)),
                ('Dette', models.FloatField(null=True)),
                ('type_facture', models.CharField(max_length=50)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='factures/')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FournisseursApp.fournisseurs')),
                ('produits', models.ManyToManyField(to='ProduitApp.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='factures/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Versement', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Dette', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('achat', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='AchatApp.achat')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='FournisseursApp.fournisseurs')),
            ],
        ),
    ]
