# Generated by Django 4.1.6 on 2023-03-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VenteApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='articles', to='VenteApp.article'),
        ),
    ]
