# Generated by Django 4.1.6 on 2023-03-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientApp', '0005_client_dette_client_email_alter_client_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='dette',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.CharField(max_length=15),
        ),
    ]
