# Generated by Django 4.1.6 on 2023-03-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProduitApp', '0006_remove_cadre_crochet_opti_remove_cadre_nombre_metre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadre',
            name='crochet_opti',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
