# Generated by Django 4.1.7 on 2023-03-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FournisseursApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseurs',
            name='Facture',
            field=models.FileField(blank=True, null=True, upload_to='invoices'),
        ),
    ]
