# Generated by Django 4.1.6 on 2023-03-27 07:23

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CategorieFer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nb_m_par_quintal', models.IntegerField()),
                ('nb_bar_par_quintal', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Categorie_fer',
                'verbose_name_plural': 'Categories_fer',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('TVA', models.FloatField(default=0)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('quantity', models.IntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('stock_alerte', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProduitApp.categorie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
        migrations.CreateModel(
            name='AutreProduit',
            fields=[
                ('produit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ProduitApp.produit')),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Autre produit',
                'verbose_name_plural': 'Autres produits',
            },
            bases=('ProduitApp.produit',),
        ),
        migrations.CreateModel(
            name='ProduitBrut',
            fields=[
                ('produit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ProduitApp.produit')),
                ('type_fer', models.CharField(choices=[('Fer /6', 'Fer /6'), ('Fer /8', 'Fer /8'), ('Fer /10', 'Fer /10'), ('Fer /12', 'Fer /12'), ('Fer /14', 'Fer /14'), ('Fer /16', 'Fer /16')], default='Fer /6', max_length=100)),
                ('stock_quintal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_barre', models.IntegerField()),
                ('stock_metre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_quintal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_metre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_barre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_achat_quintal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_achat_barre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_achat_metre', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Produit brut',
                'verbose_name_plural': 'Produits bruts',
            },
            bases=('ProduitApp.produit',),
        ),
        migrations.CreateModel(
            name='HistoriquePrixAchatQuintal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProduitApp.produitbrut')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Cadre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadre_choix', models.CharField(choices=[('Cadre', 'Cadre'), ('Octogone', 'Octogone'), ('Hexagon', 'Hexagon'), ('Losange', 'Losange'), ('Epingle', 'Epingle'), ('Crochet', 'Crochet'), ('Higes', 'Higes'), ('Senelle', 'Senelle'), ('Fiche Poteau', 'Fiche Poteau'), ('S', 'S')], default='Cadre', max_length=100)),
                ('longueur', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('largeur', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('crochet', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prix_service', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('chute', models.BooleanField(default=False)),
                ('prix_quntal', models.FloatField(default=0)),
                ('nombre_barre', models.FloatField(default=0)),
                ('consommation_sans_chute', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('consommation', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('chute_valeur', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('article_choix', models.ManyToManyField(to='ProduitApp.produitbrut')),
            ],
            options={
                'verbose_name': 'Cadre',
                'verbose_name_plural': 'Cadres',
            },
        ),
    ]
