# Generated by Django 4.1.6 on 2023-03-28 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProduitApp', '0005_rename_stock_metre_cadre_nombre_metre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadre',
            name='crochet_opti',
        ),
        migrations.RemoveField(
            model_name='cadre',
            name='nombre_metre',
        ),
        migrations.RemoveField(
            model_name='cadre',
            name='prix_metre',
        ),
    ]
