# Generated by Django 4.1.6 on 2023-03-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProduitApp', '0007_cadre_crochet_opti'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadre',
            name='prix_metre',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
