# Generated by Django 4.1.6 on 2023-03-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProduitApp', '0008_cadre_is_deleted_cadre_quantity_produit_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadre',
            name='prix',
            field=models.IntegerField(default=0),
        ),
    ]
