# Generated by Django 4.1.6 on 2023-03-15 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProduitApp', '0009_cadre_prix'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutreProduit',
            fields=[
                ('produit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ProduitApp.produit')),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Autre produit',
                'verbose_name_plural': 'Autres produits',
            },
            bases=('ProduitApp.produit',),
        ),
        migrations.CreateModel(
            name='CategorieFer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nb_m_par_quintal', models.IntegerField()),
                ('nb_bar_par_quintal', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Categorie_fer',
                'verbose_name_plural': 'Categories_fer',
            },
        ),
        migrations.AddField(
            model_name='cadre',
            name='chute_valeur',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cadre',
            name='consommation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cadre',
            name='consommation_sans_chute',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cadre',
            name='max',
            field=models.IntegerField(default=0),
        ),
    ]
