# Generated by Django 4.1.6 on 2023-03-14 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProduitApp', '0003_cadre_chute'),
        ('ProduitApp', '0005_produit_prix'),
    ]

    operations = [
    ]
