# Generated by Django 4.1.6 on 2023-03-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProduitApp', '0003_cadre_prix_metre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadre',
            name='stock_metre',
            field=models.FloatField(default=0),
        ),
    ]
