# Generated by Django 4.1.6 on 2023-03-28 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProduitApp', '0004_cadre_stock_metre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadre',
            old_name='stock_metre',
            new_name='nombre_metre',
        ),
    ]
