# Generated by Django 4.1.6 on 2023-03-28 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProduitApp', '0008_cadre_prix_metre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadre',
            name='nombre_barre',
        ),
        migrations.RemoveField(
            model_name='cadre',
            name='prix_quntal',
        ),
    ]
