# Generated by Django 4.1.7 on 2023-03-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProduitApp', '0002_produitbrut_type_fer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadre',
            name='chute',
            field=models.BooleanField(default=False),
        ),
    ]
