# Generated by Django 4.1.6 on 2023-03-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProduitApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitbrut',
            name='type_fer',
            field=models.CharField(choices=[('Fer /6', 'Fer /6'), ('Fer /8', 'Fer /8'), ('Fer /10', 'Fer /10'), ('Fer /12', 'Fer /12'), ('Fer /14', 'Fer /14'), ('Fer /16', 'Fer /16')], default='Fer /6', max_length=100),
        ),
    ]
