# Generated by Django 4.1.6 on 2023-04-02 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ClientApp', '__first__'),
        ('ProduitApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_reception', models.DateTimeField(blank=True, null=True, verbose_name='Date_reception')),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Livré', 'Livré')], max_length=200, null=True, verbose_name='Statut')),
                ('remise', models.IntegerField(default=0)),
                ('tax_amount', models.FloatField(default=0)),
                ('tax', models.FloatField(default=0)),
                ('tendered_amount', models.FloatField(default=0)),
                ('amount_change', models.FloatField(default=0)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ClientApp.client')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleCadre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=0)),
                ('prix_unite', models.IntegerField(default=0)),
                ('cadre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProduitApp.cadre', verbose_name='Cadre(s)')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VenteApp.commande')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleAutre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=0)),
                ('prix_unite', models.IntegerField(default=0)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VenteApp.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProduitApp.autreproduit', verbose_name='Autre(s) produit(s)')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unite', models.CharField(choices=[('Par barre', 'Par barre'), ('Par mètre', 'Par mètre'), ('Par quintal', 'Par quintal')], max_length=200, null=True, verbose_name='Unite')),
                ('quantite', models.IntegerField(default=1)),
                ('prix', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VenteApp.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProduitApp.produitbrut', verbose_name='Produit(s) brut(s)')),
            ],
        ),
    ]
