# Generated by Django 4.1.6 on 2023-03-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProduitApp', '0007_produit_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadre',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cadre',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='produit',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
