# Generated by Django 4.1.6 on 2023-02-17 11:44
from django.db import migrations, models
class Migration(migrations.Migration):
    dependencies = [
        ('ClientApp', '0001_initial'),
    ]
    operations = [
        migrations.RemoveField(
            model_name='customuserform',
            name='compteur_commande',
        ),
        migrations.RemoveField(
            model_name='customuserform',
            name='date_ajout',
        ),
        migrations.AddField(
            model_name='customuserform',
            name='piece_ID',
            field=models.FileField(default='media/piece_ID', upload_to='piece_ID'),
        ),
    ]