# Generated by Django 4.1.7 on 2023-02-24 19:15
from django.db import migrations
class Migration(migrations.Migration):
    dependencies = [
        ('ClientApp', '0003_client_delete_customuserform'),
    ]
    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
    ]