# Generated by Django 4.1.6 on 2023-03-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProduitApp', '0010_autreproduit_categoriefer_cadre_chute_valeur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadre',
            name='chute_valeur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cadre',
            name='consommation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cadre',
            name='consommation_sans_chute',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cadre',
            name='max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cadre',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
