# Generated by Django 4.1.6 on 2023-03-07 18:58

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ClientApp', '0005_client_dette_client_email_alter_client_type'),
        ('ProduitApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_reception', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Livré', 'Livré')], max_length=200, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ClientApp.client')),
                ('produits', models.ManyToManyField(related_name='produit', to='ProduitApp.produit')),
                ('produitsBruts', models.ManyToManyField(related_name='produitBruts', to='ProduitApp.produitbrut')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('commande', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='VenteApp.commande')),
                ('unProduit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unProduit', to='ProduitApp.produit')),
            ],
        ),
    ]
