# Generated by Django 4.1.6 on 2023-03-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VenteApp', '0005_remove_commande_articles_remove_commande_produits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('1', 'En attente'), ('2', 'Livré')], max_length=200, null=True),
        ),
    ]
