# Generated by Django 4.1.6 on 2023-04-02 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProduitApp', '0001_initial'),
        ('FournisseursApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_achat', models.DateTimeField()),
                ('prix_total', models.FloatField()),
                ('Versement', models.FloatField(null=True)),
                ('Versement_totalite', models.BooleanField(blank=True, default=False)),
                ('Dette', models.FloatField(null=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='factures/')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitBrutLiaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_quintal', models.FloatField()),
                ('quantite_metre', models.FloatField()),
                ('quantite_bar', models.FloatField()),
                ('prix_total', models.FloatField()),
                ('achat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AchatApp.achat')),
                ('produit_brut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProduitApp.produitbrut')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='factures/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Versement', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Dette', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('achat', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='AchatApp.achat')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='FournisseursApp.fournisseurs')),
            ],
        ),
        migrations.CreateModel(
            name='CadreLiaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix_total', models.FloatField()),
                ('achat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AchatApp.achat')),
                ('cadre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProduitApp.cadre')),
            ],
        ),
        migrations.CreateModel(
            name='AutreProduitLiaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.FloatField()),
                ('prix_total', models.FloatField()),
                ('achat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AchatApp.achat')),
                ('autre_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProduitApp.autreproduit')),
            ],
        ),
        migrations.AddField(
            model_name='achat',
            name='autre_produits',
            field=models.ManyToManyField(blank=True, through='AchatApp.AutreProduitLiaison', to='ProduitApp.autreproduit'),
        ),
        migrations.AddField(
            model_name='achat',
            name='cadre',
            field=models.ManyToManyField(blank=True, through='AchatApp.CadreLiaison', to='ProduitApp.cadre'),
        ),
        migrations.AddField(
            model_name='achat',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FournisseursApp.fournisseurs'),
        ),
        migrations.AddField(
            model_name='achat',
            name='produits_bruts',
            field=models.ManyToManyField(blank=True, through='AchatApp.ProduitBrutLiaison', to='ProduitApp.produitbrut'),
        ),
    ]
