# Generated by Django 4.1.6 on 2023-03-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VenteApp', '0009_articlecadre'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='remise',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articlecadre',
            name='quantite',
            field=models.IntegerField(default=0),
        ),
    ]
