# Generated by Django 4.1.6 on 2023-03-14 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProduitApp', '0009_cadre_prix'),
        ('VenteApp', '0008_alter_commande_date_reception_alter_commande_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCadre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('cadre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProduitApp.cadre')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VenteApp.commande')),
            ],
        ),
    ]
