# Generated by Django 4.1.7 on 2023-03-12 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FournisseursApp', '0001_initial'),
        ('ProduitApp', '0003_cadre_chute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_achat', models.DateTimeField()),
                ('Categorie', models.CharField(max_length=50)),
                ('Quantite_en_Quintal', models.FloatField()),
                ('Quantite_en_Bar', models.FloatField()),
                ('Quantite_en_Metre', models.FloatField()),
                ('tva_pourcentage', models.FloatField()),
                ('tva', models.FloatField()),
                ('prix', models.FloatField()),
                ('prix_total', models.FloatField()),
                ('type_facture', models.CharField(max_length=50)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FournisseursApp.fournisseurs')),
                ('produits', models.ManyToManyField(to='ProduitApp.produit')),
            ],
        ),
    ]
