# Generated by Django 4.1.6 on 2023-03-27 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ClientApp', '0001_initial'),
        ('ProduitApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_reception', models.DateTimeField(blank=True, null=True, verbose_name='Date_reception')),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Livré', 'Livré')], max_length=200, null=True, verbose_name='Statut')),
                ('remise', models.IntegerField(default=0)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ClientApp.client')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleCadre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=0)),
                ('cadre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProduitApp.cadre')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VenteApp.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VenteApp.commande')),
                ('unProduit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProduitApp.produit')),
            ],
        ),
    ]
