# Generated by Django 4.1.6 on 2023-03-13 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProduitApp', '0005_produit_prix'),
        ('VenteApp', '0003_remove_article_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VenteApp.commande'),
        ),
        migrations.AlterField(
            model_name='article',
            name='unProduit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProduitApp.produit'),
        ),
    ]
