# Generated by Django 4.1.6 on 2023-04-09 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AchatApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achat',
            name='cadre',
        ),
        migrations.DeleteModel(
            name='CadreLiaison',
        ),
    ]
