# Generated by Django 4.1.6 on 2023-03-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProduitApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadre',
            name='crochet_opti',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
