# Generated by Django 4.1.6 on 2023-04-02 11:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=40)),
                ('nom', models.CharField(max_length=40)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('type', models.CharField(choices=[('Particulier', 'Particulier'), ('Professionnel', 'Professionel')], max_length=200, null=True)),
                ('adresse', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20)),
                ('dette', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('piece_ID', models.FileField(blank=True, upload_to='piece_ID')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
