# Generated by Django 4.1.6 on 2023-03-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProduitApp', '0006_merge_0003_cadre_chute_0005_produit_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
