# Generated by Django 4.1.6 on 2023-03-13 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VenteApp', '0002_commande_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='prix',
        ),
    ]
